-ifndef(TRANSACTIONS_HRL).

-include_lib("whistle/include/wh_types.hrl").
-include_lib("whistle/include/wh_log.hrl").

-define(TOPUP_CONFIG, <<"topup">>).

%% NOTE: within each category anything bigger than 500
%%  is a credit.  So 1001 is a per minute charge and
%%  1501 is a per minute refund.

-define(CODE_UNKNOWN_DEBIT, 0000).

%% 1XXX - Usage
-define(CODE_USAGE_DEBIT, 1000).
-define(CODE_PER_MINUTE_CALL_DEBIT, 1001).
-define(CODE_SUB_ACCOUNT_PER_MINUTE_CALL_DEBIT, 1002).
-define(CODE_USAGE_CREDIT, 1500).
-define(CODE_PER_MINUTE_CALL_CREDIT, 1501).
-define(CODE_SUB_ACCOUNT_PER_MINUTE_CALL_CREDIT, 1502).

%% 2xxx - One-off
-define(CODE_ONE_OFF_DEBIT, 2000).
-define(CODE_FEATURE_ACTIVATION_DEBIT, 2001).
-define(CODE_SUB_ACCOUNT_FEATURE_ACTIVATION_DEBIT, 2002).
-define(CODE_NUMBER_ACTIVATION_DEBIT, 2003).
-define(CODE_SUB_ACCOUNT_NUMBER_ACTIVATION_DEBIT, 2004).
-define(CODE_ONE_OFF_CREDIT, 2500).
-define(CODE_FEATURE_ACTIVATION_CREDIT, 2501).
-define(CODE_SUB_ACCOUNT_FEATURE_ACTIVATION_CREDIT, 2502).
-define(CODE_NUMBER_ACTIVATION_CREDIT, 2503).
-define(CODE_SUB_ACCOUNT_NUMBER_ACTIVATION_CREDIT, 2504).

%% 3xxx - Kazoo credit management
-define(CODE_DEBIT, 3000).
-define(CODE_MANUAL_ADDITION_DEBIT, 3001).
-define(CODE_SUB_ACCOUNT_MANUAL_ADDITION_DEBIT, 3002).
-define(CODE_AUTO_ADDITION_DEBIT, 3003).
-define(CODE_SUB_ACCOUNT_AUTO_ADDITION_DEBIT, 3004).
-define(CODE_ADMIN_DISCRETION_DEBIT, 3005).
-define(CODE_TOPUP_DEBIT, 3006).
-define(CODE_CREDIT, 3500).
-define(CODE_MANUAL_ADDITION_CREDIT, 3501).
-define(CODE_SUB_ACCOUNT_MANUAL_ADDITION_CREDIT, 3502).
-define(CODE_AUTO_ADDITION_CREDIT, 3503).
-define(CODE_SUB_ACCOUNT_AUTO_ADDITION_CREDIT, 3504).
-define(CODE_ADMIN_DISCRETION_CREDIT, 3505).
-define(CODE_TOPUP_CREDIT, 3506).

%% 4xxx - Maintenance / corrections
-define(CODE_DATABASE_ROLLUP_DEBIT, 4000).
-define(CODE_DATABASE_ROLLUP_CREDIT, 4500).

%% 5xxx - Recurring
-define(CODE_RECURRING_DEBIT, 5000).
-define(CODE_MONTHLY_RECURRING_DEBIT, 5001).
-define(CODE_RECURRING_DEBIT_PRORATE, 5002).
-define(CODE_RECURRING_CREDIT, 5500).
-define(CODE_MONTHLY_RECURRING_CREDIT, 5501).
-define(CODE_RECURRING_CREDIT_PRORATE, 5502).

-define(CODE_UNKNOWN_CREDIT, 9999).

-define(TRANSACTIONS_HRL, 'true').
-endif.
